---
roles:
  - src: ironicbadger.bash_aliases
    version: "1.0.3"
  - src: grog.package
    version: "v1.4.1"
  - src: geerlingguy.docker
    version: "7.5.3"
  - name: micxer.zfs
    version: "v1.0.1"
  - src: dbrennand.autorestic
    version: "2.3.0"
  - src: micxer.docker_compose_homestack
    version: "v2.8.0"

collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: prometheus.prometheus
    version: "0.27.0"
