---
roles:
  - src: ironicbadger.bash_aliases
  - src: grog.package
  - src: geerlingguy.docker
  - name: mrlesmithjr.zfs
    src: git+https://github.com/mrlesmithjr/ansible-zfs.git
  - src: dbrennand.autorestic
  - src: micxer.docker_compose_homestack

collections:
  - ansible.posix
#   - prometheus.prometheus
