roles:
  - src: ironicbadger.bash_aliases
  - src: micxer.docker_compose_generator
  - src: grog.package
  - src: geerlingguy.docker
  # - src: micxer.zfs
  - name: micxer.zfs
    src: git+https://github.com/micxer/ansible-role-zfs.git
    version: manage-key-file

# collections:
#   - prometheus.prometheus
