---
- hosts: memoryalpha
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: geerlingguy.docker
    - role: grog.package
    #  Incompatible with Ansible 2.15.2
    # - role: prometheus.prometheus.node_exporter
    #   tags: prom

