---
- name: Make sure target path exists
  ansible.builtin.file:
    path: "{{ backup_script_path }}"
    state: directory
    mode: "0755"

- name: Copy all backup hook scripts with variable replacement
  ansible.builtin.template:
    src: "{{ template_file }}"
    dest: "{{ backup_script_path }}/{{ template_file | basename | regex_replace('\\.j2$', '') }}"
    mode: "0755"
  loop: "{{ query('ansible.builtin.fileglob', '{{ role_path }}/templates/*') }}"
  loop_control:
    loop_var: template_file
