---
# Get unique list of groups to create on the server
- name: Create list of groups
  ansible.builtin.set_fact:
    user_mgmt_groups_as_list: "{{ (user_mgmt_groups_as_list | default([]) + (item.groups | default([]))) | map('trim') | sort | unique }}"
  loop: "{{ users }}"
  when: item.groups is defined
  loop_control:
    label: "groups_as_list: {{ item.groups if item.groups is defined else '' }}"

- name: Create primary groups before adding users to group
  ansible.builtin.group:
    name: "{{ item.primarygroup }}"
    gid: "{{ item.primarygid | default(omit) }}"
    state: present
  when: item.primarygroup is defined
  loop: "{{ users }}"
  loop_control:
    label: >-
      primarygroup: {{ item.primarygroup if item.primarygroup is defined else '' }},
      primarygid: {{ item.primarygid if item.primarygid is defined else 'default' }}

- name: Create secondary groups before adding users to group
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  when: user_mgmt_groups_as_list is defined
  loop: "{{ user_mgmt_groups_as_list }}"
  loop_control:
    label: "groups: {{ item }}"

- name: Add and configure user accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit, True) }}"
    password: "{{ item.password if item.password is defined else '!' }}"
    update_password: always
    group: "{{ item.primarygroup | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell if item.shell is defined else user_mgmt_default_shell }}"
    createhome: "{{ item.createhome | default(true) }}"
    system: "{{ item.system | default(omit) }}"
    comment: "{{ item.comment if item.comment is defined else '' }}"
    state: present # intentionally no deletion of users
    expires: -1 # no expiry
  when: (item.user_state == 'present' or item.user_state == 'lock')
  loop: "{{ users }}"
  loop_control:
    label: >-
      username: {{ item.username }}, user_state: {{ item.user_state }}, password: {{ 'True' if item.password is defined else 'False' }},
      primarygroup: {{ item.primarygroup if item.primarygroup is defined else '' }}, groups: {{ item.groups if item.groups is defined else '' }}

- name: Add SSH keys for users
  ansible.posix.authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    exclusive: >-
      {{ (item.2 == 0) | ternary(item.0.exclusive_ssh_key if item.0.exclusive_ssh_key is defined else 'no', 'no') }}
    path: "{{ '/home/' + item.0.username + '/.ssh/authorized_keys' if ansible_check_mode else omit }}"
    state: present
  when: item.1 is defined
  loop: >-
    {{ users | map('combine', {'ssh_keys': (item.ssh_key if item.ssh_key is iterable and item.ssh_key is not string else [item.ssh_key])})
       | map('combine', {'ssh_keys_indexed': ssh_keys | zip(range(ssh_keys | length))})
       | subelements('ssh_keys_indexed') }}
  loop_control:
    label: >-
      username: {{ item.0.username }}, ssh_key: {{ 'True' if item.1 is defined else 'False' }},
      exclusive_ssh_key: {{ (item.2 == 0) | ternary(item.0.exclusive_ssh_key if item.0.exclusive_ssh_key is defined else 'no', 'no') }}
