---
docker_compose_generator_output_path: "~"
docker_compose_generator_uid: "1000"
docker_compose_generator_gid: "1000"

docker_compose_generator_nextcloud_active: true
# docker_compose_generator_nextcloud_base_path: ""  # must be set
docker_compose_generator_nextcloud_user: "www-data"
docker_compose_generator_nextcloud_group: "www-data"
# docker_compose_generator_nextcloud_image: # must be set
