---
- name: ensure target dir exists
  file:
    dest: "{{ traefik_config_path }}"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"

- name: template traefik config
  template:
    src: templates/traefik.yaml.j2
    dest: "{{ traefik_config_path }}/traefik.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  tags: traefik

- name: copy traefik rules
  template:
    src: templates/config.yaml.j2
    dest: "{{ traefik_config_path }}/config.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  when: traefik_file_provider
  tags: traefik