---
- name: Ensure target dir exists
  ansible.builtin.file:
    dest: "{{ traefik_config_path }}"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
    mode: "0755"

- name: Template traefik config
  ansible.builtin.template:
    src: templates/traefik.yaml.j2
    dest: "{{ traefik_config_path }}/traefik.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
    mode: "0600"

- name: Copy traefik rules
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: "{{ traefik_config_path }}/config.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
    mode: "0600"
  when: traefik_file_provider
