---
- hosts: memoryalpha
  vars_files:
    - '../vars/vault.yml'
  roles:
    - role: grog.package
      tags: packages
    - role: geerlingguy.docker
      tags: docker
    - role: user_mgmt
      tags: users
    #  Incompatible with Ansible 2.15.2
    # - role: prometheus.prometheus.node_exporter
    #   tags: prom
    - role: ironicbadger.bash_aliases
      tags: bash_aliases
    - role: mrlesmithjr.zfs
      tags: zfs
    - role: traefik
      tags: docker_compose
    - role: micxer.docker_compose_generator
      tags: docker_compose