---

- hosts: all
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Upgrade packages on all Debian/Ubuntu boxes
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        force_apt_get: true
        upgrade: true
    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required get_checksum=false
    - name: Reboot the box if kernel updated
      when: reboot_required_file.stat.exists
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
