name: ansible-lint
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint Ansible Playbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Create file .vault-password
        run: |
          echo "foo" > .vault-password
          chmod 600 .vault-password

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c # v26

      - name: Upload Sarif file
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4
        with:
          sarif_file: ansible-lint.sarif
        if: always()